### ISSUE TITLE
some todos

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#1]
@EvonX implement the methods to crawl the `dockerfile` given an image name
@cutylewiwi implement the interface (using a `map`) to store the files and their MD5 hashes
@cutylewiwi try on the official images to see if the code can work for all the images

**Comment by tianyin** [comment]
@EvonX when you crawl the `dockerfile`, can you also crawl and parse the tag files? like this one,
https://hub.docker.com/r/library/httpd/tags/

right now, there's no direct way to know the tags given an image.

**Comment by EvonX** [comment]
@tianyin Sure. I found there is a json web service from dockerhub that makes it easy:
`curl -L -s 'https://registry.hub.docker.com/v2/repositories/library/httpd/tags?page_size=1024'|jq '."results"[]["name"]'`

BTW, this [repo](https://github.com/harisekhon/pytools) has some interesting tools related to docker.

**Comment by tianyin** [comment]
@EvonX this is awesome!!!!!!

**Comment by tianyin** [comment]
@EvonX the service is awesome, and saves whole lots of efforts of parsing. Is there any service for querying the tags (versions)?

**Comment by EvonX** [comment]
Yes, the one line curl cmd I posted before can get the tags of a repo.

And we can get even more than just tags!!!
For an unofficial repo, we can get "repo info", ''tags", and "dockerfile" with the [Docker Registry HTTP API V2](https://docs.docker.com/registry/spec/api/). Here are some rules:

- info: `https://registry.hub.docker.com/v2/repositories/<user>/<app>/`
  e.g. [https://registry.hub.docker.com/v2/repositories/webdevops/nginx/](https://registry.hub.docker.com/v2/repositories/webdevops/nginx/)

- tags: `https://registry.hub.docker.com/v2/repositories/<user>/<app>/tags/`
  e.g. [https://registry.hub.docker.com/v2/repositories/webdevops/nginx/tags/](https://registry.hub.docker.com/v2/repositories/webdevops/nginx/tags/)

- dockerfile: `https://registry.hub.docker.com/v2/repositories/<user>/<app>/dockerfile/`
  e.g. [https://registry.hub.docker.com/v2/repositories/webdevops/nginx/dockerfile/](https://registry.hub.docker.com/v2/repositories/webdevops/nginx/dockerfile/)

For official repos, the user is just `library`, but the dockerfile cannot be accessed through this approach. The good thing is their `info` usually contain links to their dockerfiles, e.g. [https://registry.hub.docker.com/v2/repositories/library/httpd/](https://registry.hub.docker.com/v2/repositories/library/httpd/). So we can use that to download the dockerfile.

**Comment by tianyin** [comment]
This is very good. Basically we can easily get all the metadata and build the understanding before downloading all the big images.

~t

**Comment by EvonX** [comment]
Yes, exactly.

**Comment by tianyin** [comment]
[like]

**Comment by tianyin** [comment]
close by c193af7eef4c92a8cbffc9cd10eb2163d7d208c9
