### ISSUE TITLE
normalize the tag stuff based on image id

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#10]
@EvonX can you take care of this part?

basically, as we discussed, there could be multiple tags pointing to the same image (identified by image id). We don't want to run the same image multiple times.

**Comment by EvonX** [comment]
Sure~

**Comment by tianyin** [comment]
@EvonX you should focus on the proj meeting tmr; this is not a blocking issue.

**Comment by EvonX** [comment]
@tianyin I see, thx.

**Comment by EvonX** [comment]
write `crawl/authed_crawler_db.py` to crawl image id with the authenticated registry api.

**Comment by tianyin** [comment]
so close it?

**Comment by EvonX** [comment]
Yes.
