### ISSUE TITLE
bug: resource cleaning

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#12]
the current `fsaudit` does not do resource cleaning. Running the audit starts a new container on the OS which cannot scale. Imagine also needs to scale as the disk space is limited.

**Comment by cutylewiwi** [comment]
Current it cleans up the container start by `fsaudit`, but not cleans up the images pull down

**Comment by tianyin** [comment]
let's keep it for now and leave it open. I'm not sure the consequence of not cleaning the images.
