### ISSUE TITLE
understand `sys/device`

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#16]
@cutylewiwi it turns out that a huge number of file diffs between two different OS setups are from the `sys/device` directory. 

Can you investigate the `sys/device` directory? If the content is based on the host OS and cannot be manipulated by the image author, we can completely ignore this directory. 

This has the potential of saving huge number of md5 calculation and thus accelerate the `fsaudit` process.

**Comment by tianyin** [comment]
https://www.centos.org/docs/5/html/5.1/Installation_Guide/s1-s390info-sysfs.html
https://www.quora.com/What-is-the-purpose-of-sys-directory-in-Linux
https://superuser.com/questions/794198/directory-sys-in-linux
https://askubuntu.com/questions/720471/whats-the-sys-directory-for

@EvonX seems `/sys` can be ignored?

**Comment by EvonX** [comment]
@tianyin Yes, seems can be ignored.

**Comment by tianyin** [comment]
@EvonX it's better to understand how Docker does it... 
@cutylewiwi can you do the investigation?

**Comment by tianyin** [comment]
perhaps one way of hacking around is to download an image, put a new file in some dirs in `/sys/devices` and republish it. And see what would be the new image look like. 

~t

**Comment by cutylewiwi** [comment]
@tianyin I will do that

**Comment by tianyin** [comment]
cool.

**Comment by tianyin** [comment]
A little more information (or say confirmation):

```
---------- ubuntu@cutylewiwi-OptiPlex-5040 ----------
/bin 77
/etc 168
/lib 345
/run 4
/sbin 65
/sys 18856
/usr 3091
/var 508
---------- ubuntu@cutylewiwis-MacBook-Pro.local ----------
/bin 77
/etc 168
/lib 345
/run 4
/sbin 65
/sys 5694
/usr 3091
/var 508
---------- ubuntu@tianyin-h8-1160t ----------
/bin 77
/etc 168
/lib 345
/run 4
/sbin 65
/sys 19469
/usr 3091
/var 508
```
We can see only `/sys` has different number of files.

```
---------- ubuntu@cutylewiwi-OptiPlex-5040 ----------
/sys/bus 54
/sys/class 3
/sys/devices 13494
/sys/fs 172
/sys/kernel 3408
/sys/module 1711
/sys/power 14
---------- ubuntu@cutylewiwis-MacBook-Pro.local ----------
/sys/bus 23
/sys/class 1
/sys/devices 4847
/sys/fs 220
/sys/kernel 261
/sys/module 338
/sys/power 4
---------- ubuntu@tianyin-h8-1160t ----------
/sys/bus 51
/sys/class 3
/sys/devices 13426
/sys/firmware 136
/sys/fs 199
/sys/kernel 4069
/sys/module 1571
/sys/power 14
```
All most all the subdirs of `/sys` have different number of files.

**Comment by tianyin** [comment]
close (refer to #19 )
