### ISSUE TITLE
centos:7 container gets stuck when I run fsaudit on it

### ISSUE THREAD

**Issue by EvonX** [tianyin/rekcod#17]
This may be a problem related to my system. I found the reason is that some files cannot be read in my centos container.  The container immediately gets stuck when I cat some files, e.g. `/sys/module/rcutree/parameters/rcu_fanout_leaf`. @cutylewiwi @tianyin could you pls check the file content for me? Thanks.

**Comment by tianyin** [comment]
how can we check the file content for you?

**Comment by EvonX** [comment]
`docker run -it --name my-centos centos:7 `
`cat /sys/module/rcutree/parameters/rcu_fanout_leaf`
`docker rm -f my-centos`

**Comment by tianyin** [comment]
The file content on my docker is simply 
```
64
```

**Comment by tianyin** [comment]
close it for now.
