### ISSUE TITLE
Would this be a way to narrow down different files 

### ISSUE THREAD

**Issue by EvonX** [tianyin/rekcod#18]
How about download an image's dockerfile, create a new image with a corresponding simplified dockerfile, which just includes `from` and `apt-get` cmd from the original dockerfiles, and then compare the downloaded image with the image we created? In this way we bypass different library files and only get the files created by the image maker.

**Comment by tianyin** [comment]
hmmm.... i'm not too sure about it...
essentially, what we want to tell ppl is the file diffs from a statistical perspective. 
I'm not sure about ignoring `apt-get` and other libs (remember the argument of "attack surface")

Let's still keep the current one, and see how much we can opt after removing all the machine dependent stuff.

**Comment by EvonX** [comment]
I see, make sense.
