### ISSUE TITLE
understand /sys and /proc

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#19]
need to understand how docker creates `/sys` and `/proc`
if we publish a docker image by copying stuff into `/proc` and `/sys`, 
what will the image look like?

**Comment by tianyin** [comment]
so i guess the current solution is to skip these two parts?
close it for now. 
@cutylewiwi you'll write the corresponding section in the final report.

~t

**Comment by cutylewiwi** [comment]
/sys and /proc are linux pseudo file systems. Basically, they expose some linux kernel data structures like process file descriptors and virtual memory mapping (which is in /proc/pid).

Most of procfs is readonly, the writable files are interface to change the kernel variables. 

Sysfs is a ram-based filesystem initially based on ramfs, they expose kernel data structures, their attributes, and the linkages between them to userspace.

As test in the real images, sysfs is mounted as read only file systems, and when remount, it will failed with permission denied. procfs is mounted as read write, but /proc fs permission is read only. Even if change /proc fs permission to read write, when try to create files and directories i.n /proc, it will be denied.

Another test with the real images, when export file system from a container, the exported file system will only has empty /proc and /sys path.
