### ISSUE TITLE
determine Linux distribution name and version

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#2]
@cutylewiwi since we already run `fsaudit` inside a container; can you also run a script to find out the Linux distribution name and version. You can use commands in the following link,
https://www.cyberciti.biz/faq/find-linux-distribution-name-version-number/

**Comment by tianyin** [comment]
reassigned to @EvonX 
@EvonX you can ask @cutylewiwi for running cmd inside a running container.

**Comment by tianyin** [comment]
@cutylewiwi @EvonX there's some mysterious about running the nodejs container...

**Comment by EvonX** [comment]
`get_dist_info()` and `get_kernel_info()` in `os_inspect.py` can extract distribution name, version and kernel version now.

**Comment by tianyin** [comment]
@EvonX awesome. feel free to close the issue if it's implemented.

~t
