### ISSUE TITLE
day 2: make sense of data

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#22]
1. get the number of os file paths and app file paths

 2. get the number of os file md5 and app file md5

3. get the number of `diff` of os file paths (bet. official and curr)

4. get the number of `diff` of file md5 (bet. official and curr)

5. for the file that diffs, get the statistics of the popularity of this file among all the images

**Comment by EvonX** [comment]
1-4 are available in `analyse/`. Following is the file name and column explanation

1. `os_app_filepath.count`: \<imgname\> \<os file count\> \<app file count\>
2. `os_app_md5.count`: \<imgname\> \<os md5 count\> \<app md5 count\>
3. `os_filepath.diff`: \<imgname\> \<different os file count\> \<removed os file count\>
4. `app_md5.diff`: \<imgname\> \<added md5 count\> \<removed md5 count\>

**Comment by tianyin** [comment]
this is superb! 
let's take a close look at the data to understand the diffs in depth. 
thanks, @EvonX !
