### ISSUE TITLE
Official OS Images Cannot Get Release Description

### ISSUE THREAD

**Issue by cutylewiwi** [tianyin/rekcod#23]
Some official os images cannot get image release description. Here is the list:

crux
clearlinux

**Comment by EvonX** [comment]
`Alpine Linux 3.5.0` not found cause `agaveapi.httpd:2.4` and `codeclou.docker-apache-httpd-php-develop:latest` failed.

**Comment by tianyin** [comment]
i think at this moment, let's skip this if the affected # is small.

~t
