### ISSUE TITLE
fix the first TODO in 1.3

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#27]
@cutylewiwi 
again, we need to prove the concept.

**Comment by cutylewiwi** [comment]
A test example I did:

In a running ubuntu:latest container, I mv /bin/bash to /bin/bash1, and create a executable shell script named bash in /bin, with content:

```
#!/bin/bash1

echo "I am a bad guy"

/bin/bash1
```

Then commit this container to a new image (let's say, fakeubuntu)

When running this new image, as the entry point for the image is /bin/bash, then the script I introduced before will be execute, thus the `echo` command executed.

**Comment by cutylewiwi** [comment]
BTW where should I put this demostrate?

**Comment by tianyin** [comment]
this is cool. 
let me write it down.

**Comment by tianyin** [comment]
also, can you list the Dockerfile and the `history` here,
I probably use this example to replace the one in the current Appendix B.

**Comment by cutylewiwi** [comment]
Sure, wait a moment

**Comment by cutylewiwi** [comment]
Dockerfile:

```
FROM ubuntu:latest
RUN mv /bin/bash /bin/bash1
COPY bash /bin/
```

**Comment by tianyin** [comment]
can you print the original output of `docker history` here?

**Comment by cutylewiwi** [comment]
related history in metadata:

{"created":"2017-06-13T22:12:32.360294191Z","created_by":"/bin/sh -c mv /bin/bash /bin/bash1"},
{"created":"2017-06-13T22:12:32.952575626Z","created_by":"/bin/sh -c #(nop) COPY file:743dd1c88a4fcae5cca6cff4564df121222c95ab3c9582b8fb1171e2a6180fbf in /bin/ "}

docker history result:
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
72185d942df4        3 minutes ago       /bin/sh -c #(nop) COPY file:743dd1c88a4fca...   47 B                
9f31cdd35e43        3 minutes ago       /bin/sh -c mv /bin/bash /bin/bash1              1.04 MB             
7b9b13f7b9c0        11 days ago         /bin/sh -c #(nop)  CMD ["/bin/bash"]            0 B                 
<missing>           11 days ago         /bin/sh -c mkdir -p /run/systemd && echo '...   7 B                 
<missing>           11 days ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\...   2.76 kB             
<missing>           11 days ago         /bin/sh -c rm -rf /var/lib/apt/lists/*          0 B                 
<missing>           11 days ago         /bin/sh -c set -xe   && echo '#!/bin/sh' >...   745 B               
<missing>           11 days ago         /bin/sh -c #(nop) ADD file:5aff8c59a707833...   118 MB

**Comment by cutylewiwi** [comment]
related lines:

72185d942df4        3 minutes ago       /bin/sh -c #(nop) COPY file:743dd1c88a4fca...   47 B                
9f31cdd35e43        3 minutes ago       /bin/sh -c mv /bin/bash /bin/bash1              1.04 MB

**Comment by tianyin** [comment]
can you give me all the lines?

**Comment by tianyin** [comment]
oh, it's on the top (i missed it)
thanks!
