### ISSUE TITLE
finish plotting the statistics

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#30]
need a few more figures that follow the decision logic (see Figure 3)

**Comment by tianyin** [comment]
@cutylewiwi can you also help include these figures into Section 4? 
you can just copy and paste the command in `results.tex` to insert figures and subfigures.

**Comment by cutylewiwi** [comment]
I would like to help.

BTW I will change any match in my figures to content match as it seems that you changed this term this morning....

**Comment by tianyin** [comment]
cool

**Comment by tianyin** [comment]
waiting for your `results.tex`

**Comment by cutylewiwi** [comment]
By insert the figures we already have 5 1/4 page....

**Comment by cutylewiwi** [comment]
pushed a version, all fig insert, but I am still working on descriptions....

**Comment by tianyin** [comment]
no worry about the desc, right now.
desc are written after we can make sense of the data.
(there's no point to do it at this moment)
