### ISSUE TITLE
findings

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#32]
1. again, what are the files that are different?
2. can we find malice and mistakes?
3. what can we do about the diff files?
   - for binary 
   - for config files (can we do more fine-grained analysis?)

**Comment by EvonX** [comment]
suffix count of the most suspicious (diff file miss md5) filepath:

[(u'.x86_64', 1),
 (u'.def', 1),
 (u'.org_debian_dists_jessie_Release', 1),
 (u'.gb18030/Compose', 1),
 (u'.d/sshd', 1),
 (u'.d/supervisor', 1),
 (u'.types', 1),
 (u'.11/py-compile', 1),
 (u'.css', 1),
 (u'.sub', 1),
 (u'.in', 1),
 (u'.4/bin/pg_controldata', 1),
 (u'.perl', 1),
 (u'.el7_2-x86_64/command_line', 1),
 (u'.gbk/Compose', 1),
 (u'.4/bin/pgbench', 1),
 (u'.mysqld', 1),
 (u'.el7_1-noarch/command_line', 1),
 (u'.1-x86_64/origin_url', 1),
 (u'.3-noarch/command_line', 1),
 (u'.dtd', 1),
 (u'.global', 1),
 (u'.exp', 1),
 (u'.tcvn/XLC_LOCALE', 1),
 (u'.JIS/Compose', 1),
 (u'.4/bin/vacuumlo', 1),
 (u'.bfd', 1),
 (u'.d/sudo', 1),
 (u'.SJIS/Compose', 1),
 (u'.cache-4', 1),
 (u'.6-x86_64/command_line', 1),
 (u'.policy', 1),
 (u'.big5hkscs/Compose', 1),
 (u'.tcvn/Compose', 1),
 (u'.theme', 1),
 (u'.el7_0-x86_64/command_line', 1),
 (u'.11/elisp-comp', 1),
 (u'.ini', 1),
 (u'.multiple-instances', 1),
 (u'.viscii/Compose', 1),
 (u'.d/network', 1),
 (u'.phar', 1),
 (u'.el7-noarch/from_repo_revision', 1),
 (u'.4/bin/pg_xlogdump', 1),
 (u'.4/bin/pg_standby', 1),
 (u'.SJIS/XLC_LOCALE', 1),
 (u'.2-noarch/var_uuid', 1),
 (u'.sysinit', 1),
 (u'.mk', 1),
 (u'.gb18030/XLC_LOCALE', 1),
 (u'.viscii/XLC_LOCALE', 1),
 (u'.map', 1),
 (u'.4/bin/postgres', 1),
 (u'.properties', 1),
 (u'.el7_3-noarch/from_repo_revision', 1),
 (u'.el6_7-x86_64/releasever', 1),
 (u'.koi8-r', 1),
 (u'.tar', 1),
 (u'.key', 1),
 (u'.gbk/XLC_LOCALE', 1),
 (u'.4/bin/initdb', 1),
 (u'.gold', 1),
 (u'.lefty', 1),
 (u'.alias', 1),
 (u'.p11-kit', 1),
 (u'.4/bin/pg_ctl', 1),
 (u'.dafsa', 1),
 (u'.daily/apache2', 1),
 (u'.15', 1),
 (u'.com_ubuntu_dists_xenial_InRelease', 1),
 (u'.js', 1),
 (u'.4/bin/pg_test_fsync', 1),
 (u'.el7_0-x86_64/var_uuid', 1),
 (u'.JIS/XLC_LOCALE', 1),
 (u'.d/git', 1),
 (u'.el7_2-x86_64/from_repo_timestamp', 1),
 (u'.d/mysql', 1),
 (u'.backtrace', 1),
 (u'.d/polkit-1', 1),
 (u'.el7-x86_64/from_repo_revision', 1),
 (u'.cnf', 1),
 (u'.desktop', 1),
 (u'.2-noarch/from_repo_revision', 1),
 (u'.shlibs', 1),
 (u'.big5hkscs/XLC_LOCALE', 1),
 (u'.el6-noarch/from_repo_revision', 1),
 (u'.xz', 1),
 (u'.4/bin/pg_test_timing', 1),
 (u'.el7_1-noarch/from_repo_timestamp', 1),
 (u'.pdf', 1),
 (u'.tri', 1),
 (u'.el7_0-x86_64/from_repo_timestamp', 1),
 (u'.tif', 1),
 (u'.nice', 1),
 (u'.2-noarch/from_repo_timestamp', 1),
 (u'.4/bin/pg_resetxlog', 1),
 (u'.el6_6-x86_64/releasever', 1),
 (u'.9', 1),
 (u'.bin', 1),
 (u'.d/mysql-server', 1),
 (u'.el6-noarch/from_repo_timestamp', 1),
 (u'.c', 1),
 (u'.4/bin/pg_archivecleanup', 1),
 (u'.org_debian_dists_jessie-updates_InRelease', 1),
 (u'.6-x86_64/origin_url', 1),
 (u'.com_ubuntu_dists_xenial-updates_InRelease', 1),
 (u'.guess', 1),
 (u'.11/mdate-sh', 1),
 (u'.org_dists_jessie_updates_InRelease', 1),
 (u'.ent', 1),
 (u'.27', 1),
 (u'.26', 1),
 (u'.4/bin/oid2name', 1),
 (u'.3-noarch/from_repo_revision', 1),
 (u'.gpg', 1),
 (u'.11/ylwrap', 1),
 (u'.4/bin/pg_upgrade', 1),
 (u'.004', 1),
 (u'.002', 1),
 (u'.003', 1),
 (u'.001', 1),
 (u'.cfg', 1),
 (u'.02', 2),
 (u'.fc24-x86_64/checksum_data', 2),
 (u'.4-x86_64/from_repo_revision', 2),
 (u'.2-x86_64/releasever', 2),
 (u'.nanorc', 2),
 (u'.d/apache2', 2),
 (u'.3-x86_64/releasever', 2),
 (u'.big5/Compose', 2),
 (u'.sample', 2),
 (u'.8-x86_64/from_repo_timestamp', 2),
 (u'.dist', 2),
 (u'.5m/Makefile', 2),
 (u'.42', 2),
 (u'.el7_1-noarch/var_uuid', 2),
 (u'.7-x86_64/from_repo_revision', 2),
 (u'.7-x86_64/from_repo_timestamp', 2),
 (u'.rst', 2),
 (u'.4-x86_64/command_line', 2),
 (u'.centos-x86_64/releasever', 2),
 (u'.22', 2),
 (u'.el7_1-x86_64/from_repo_timestamp', 2),
 (u'.big5/XLC_LOCALE', 2),
 (u'.el7_1-x86_64/command_line', 2),
 (u'.3-noarch/from_repo_timestamp', 2),
 (u'.1e', 2),
 (u'.crt', 2),
 (u'.centos-noarch/var_uuid', 2),
 (u'.11', 2),
 (u'.el7_3-noarch/command_line', 2),
 (u'.3-x86_64/from_repo_revision', 2),
 (u'.7-x86_64/var_uuid', 2),
 (u'.dat-old', 2),
 (u'.centos-noarch/releasever', 2),
 (u'.3-noarch/var_uuid', 2),
 (u'.cramfs', 2),
 (u'.5m', 2),
 (u'.cache', 2),
 (u'.preset', 2),
 (u'.8-x86_64/from_repo_revision', 2),
 (u'.repo', 2),
 (u'.lock', 2),
 (u'.awk', 2),
 (u'.preinst', 2),
 (u'.8-x86_64/var_uuid', 2),
 (u'.el7_2-x86_64/var_uuid', 2),
 (u'.local', 2),
 (u'.dir', 2),
 (u'.el6_9-x86_64/releasever', 3),
 (u'.dat', 3),
 (u'.svg', 3),
 (u'.3-x86_64/command_line', 3),
 (u'.postrm', 3),
 (u'.el6_9-x86_64/from_repo_timestamp', 3),
 (u'.el7_3-noarch/var_uuid', 3),
 (u'.el6_9-x86_64/from_repo_revision', 3),
 (u'.sh', 3),
 (u'.el7_3-noarch/from_repo_timestamp', 3),
 (u'.centos-x86_64/var_uuid', 3),
 (u'.4-x86_64/from_repo_timestamp', 4),
 (u'.2-x86_64/from_repo_revision', 4),
 (u'.pub', 4),
 (u'.el7_1-x86_64/var_uuid', 4),
 (u'.pem', 4),
 (u'.2-x86_64/command_line', 4),
 (u'.jpg', 4),
 (u'.pt-br', 4),
 (u'.4-x86_64/var_uuid', 4),
 (u'.5', 4),
 (u'.6', 4),
 (u'.o', 4),
 (u'.m4f', 4),
 (u'.pc', 5),
 (u'.conffiles', 5),
 (u'.el6-noarch/releasever', 5),
 (u'.3-x86_64/from_repo_timestamp', 5),
 (u'.1-x86_64/releasever', 6),
 (u'.sqlite-journal', 6),
 (u'.t', 6),
 (u'.service', 6),
 (u'.3-x86_64/var_uuid', 7),
 (u'.el6_8-x86_64/from_repo_timestamp', 7),
 (u'.el6_8-x86_64/from_repo_revision', 7),
 (u'.el6_8-x86_64/releasever', 7),
 (u'.chk', 8),
 (u'.2-x86_64/from_repo_timestamp', 8),
 (u'.2-x86_64/var_uuid', 8),
 (u'.1-x86_64/command_line', 8),
 (u'.sqlite', 8),
 (u'.3', 8),
 (u'.hmac', 8),
 (u'.prerm', 9),
 (u'.8', 9),
 (u'.postinst', 10),
 (u'.el7_3-x86_64/command_line', 10),
 (u'.txt', 11),
 (u'.a', 12),
 (u'.1-x86_64/from_repo_revision', 13),
 (u'.el7_3-x86_64/from_repo_revision', 13),
 (u'.json', 14),
 (u'.hwdb', 14),
 (u'.4', 14),
 (u'.es', 15),
 (u'.log', 15),
 (u'.UTF-8/Compose', 15),
 (u'.md', 15),
 (u'.UTF-8/XLC_LOCALE', 15),
 (u'.el7-noarch/origin_url', 15),
 (u'.el7-x86_64/origin_url', 16),
 (u'.x', 16),
 (u'.7', 17),
 (u'.1-x86_64/var_uuid', 17),
 (u'.pl', 18),
 (u'.am', 19),
 (u'.el7-noarch/from_repo_timestamp', 19),
 (u'.1-x86_64/from_repo_timestamp', 20),
 (u'.2', 20),
 (u'.conf', 21),
 (u'.de', 21),
 (u'.sys', 23),
 (u'.el7_3-x86_64/from_repo_timestamp', 23),
 (u'.el7_3-x86_64/var_uuid', 23),
 (u'.xml', 27),
 (u'.el7-noarch/var_uuid', 29),
 (u'.db', 30),
 (u'.el7-noarch/command_line', 33),
 (u'.ph', 38),
 (u'.1', 38),
 (u'.pyo', 43),
 (u'.m4', 48),
 (u'.el6-x86_64/releasever', 49),
 (u'.0', 63),
 (u'.list', 71),
 (u'.md5sums', 74),
 (u'.euc-kr', 109),
 (u'.py', 125),
 (u'.el7-x86_64/from_repo_timestamp', 126),
 (u'.pod', 134),
 (u'.el7-x86_64/command_line', 141),
 (u'.php', 160),
 (u'.pm', 187),
 (u'.utf8', 191),
 (u'.png', 196),
 (u'.html', 201),
 (u'.fr', 206),
 (u'.el7-x86_64/var_uuid', 225),
 (u'.en', 234),
 (u'.mo', 398),
 (u'.so', 819),
 (u'.h', 859),
 (u'.gz', 1185),
 (None, 1502),
 (u'.pyc', 4730)]

**Comment by tianyin** [comment]
you used my scripts? 
it looks like the same results.

~t

**Comment by EvonX** [comment]
Nope, I write another one...and the data is not just comparing os files.

**Comment by tianyin** [comment]
you can use the `stats/diffstats.py`
anyway,,,
