### ISSUE TITLE
5 new result figures

### ISSUE THREAD

**Issue by cutylewiwi** [tianyin/rekcod#36]
Finished 5 new result figures:

- figures/anymatchedfilepercentage.eps: % files matched by md5 in all files can not exact match another file

- figures/suspiciousfilespercentage.eps: % files can match path but can not match any md5 in all files

- figures/suspiciousfiles.eps: # of files can match path but can not match any md5 in all files

- figures/unknownfilespercentage.eps: % files can not match either md5 or path

- figures/unknownfiles.eps: # of files can not match either md5 or path

**Comment by cutylewiwi** [comment]
Let me know if there is any problem in those figures...

**Comment by tianyin** [comment]
This is the same as #30 
please reply the original issue rather than creating new issues (as it's a response to it)
