### ISSUE TITLE
4.1 the db stuff

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#39]
@EvonX can you provide me with the following numbers regarding the TCB and official images (OI):

1. total # OIs we analyzed
2. total # of tags of OIs
3. total # of unique file path in all OIs
4. total # of unique md5 in all OIs
5. the storage (how many GBs) of the mongodb uses

**Comment by EvonX** [comment]
# OIs: 131
# OIs tags: 2969
# unique file path in all OIs: 1347860
# unique md5 in all OIs: 1429191
# storagesize of OI collections: 3.15GB
