### ISSUE TITLE
Figure 4(a)

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#40]
We can see that the match based on trust base can effectively identify the majority (50+\%) of
files in more than XX\% of the images. 
In XX\% of the images, more than 90\% of the files can be matched.

**Comment by tianyin** [comment]
Also, we can see that content match is useful, as it can cover
a significant percentage (up to XX\%) of files that are missed by exact match.

**Comment by cutylewiwi** [comment]
We can see that the match based on trust base can effectively identify the majority (50+%) of
files in more than 96% of the images.
In 63% of the images, more than 90% of the files can be matched.

**Comment by cutylewiwi** [comment]
Also, we can see that content match is useful, as it can cover
a significant percentage (up to 88.48%) of files that are missed by exact match.
